name: webdriver
author: "Dart Team <misc@dartlang.org>"
homepage: http://www.dartlang.org
description: >
 Provides WedDriver bindings for Dart. These use the WebDriver JSON
 interface, and as such, require the use of the WebDriver remote server.

