# Copyright (c) 2011, the Dart project authors.  Please see the AUTHORS file
# for details. All rights reserved. Use of this source code is governed by a
# BSD-style license that can be found in the LICENSE file.

application: google.com:dartperf
version: 1
runtime: python
api_version: 1

handlers:
- url: /(.*\.html)
  mime_type: text/html
  static_files: static/\1
  upload: static/(.*\.html)

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: static/\1
  upload: static/(.*\.js)

- url: /(.*\.txt)
  mime_type: text/html
  static_files: static/\1
  upload: static/(.*\.txt)

- url: /(.*\.json)
  mime_type: application/json
  static_files: static/\1
  upload: static/(.*\.json)

# image files
- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: static/\1
  upload: static/(.*\.(bmp|gif|ico|jpeg|jpg|png))

# index files
- url: /(.+)/
  static_files: static/\1/index.html
  upload: static/(.+)/index.html
  expiration: "15m"

- url: /(.+)
  static_files: static/\1/index.html
  upload: static/(.+)/index.html
  expiration: "15m"

- url: /graphs
  static_dir: static/graphs

- url: /graphs/(.*)
  static_files: static/graphs/\1
  upload: static/graphs/(.*)

- url: /data/browser-perf/macos/(.*)
  static_files: static/data/browser-perf/macos/\1
  upload: static/data/browser-perf/macos/(.*)

- url: /data/code-time-size/macos/(.*)
  static_files: static/data/code-time-size/macos/\1
  upload: static/data/code-time-size/macos/(.*)

- url: /data/cl-results/macos/(.*)
  static_files: static/data/cl-results/macos/\1
  upload: static/data/cl-results/macos/(.*)

# site root
- url: /
  static_files: static/index.html
  upload: static/index.html
  expiration: "15m"
