name: unittest
author: "Dart Team <misc@dartlang.org>"
homepage: http://www.dartlang.org
documentation: http://api.dartlang.org/docs/pkg/unittest
description: >
 A library for writing dart unit tests.
dependencies:
  meta: any

