name: scheduled_test
author: "Dart Team <misc@dartlang.org>"
homepage: http://www.dartlang.org
description: >
  A package for writing readable tests of asynchronous behavior.

  This package works by building up a queue of asynchronous tasks called a
  "schedule", then executing those tasks in order. This allows the tests to
  read like synchronous, linear code, despite executing asynchronously.

dependencies:
  http: ">=0.4.1 <1.0.0"
  pathos: ">=0.3.2 <1.0.0"
  stack_trace: ">=0.4.3 <1.0.0"
  unittest: ">=0.4.3 <1.0.0"
