name: http
author: "Dart Team <misc@dartlang.org>"
homepage: http://www.dartlang.org
description: A composable, Future-based API for making HTTP requests.
dependencies:
  pathos: any
dev_dependencies:
  unittest: any
